version: "2"
services:
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nodejs
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nodejs:
    build: ./node/
    volumes:
      - ./node/:/var/www/app
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=${NODE_PORT}
      - REDIS=${REDIS}
      - REDIS_PORT=${REDIS_PORT}
      - DB=${DB}
      - ORG_URL=${ORG_URL}
      - OKTA_TOKEN=${OKTA_TOKEN}
      - SESSION_SECRET=${SESSION_SECRET}
      - OKTA_ISSUER=${OKTA_ISSUER}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
      - OKTA_REDIRECT_URL=${OKTA_REDIRECT_URL}
    command:
      sh -c 'npm i && npm start'
    links:
      - redis
  pwa-backend:
    build: ./pwa-backend/kommunat/node/
    volumes:
      - ./pwa-backend/kommunat/node/:/var/www/app
    ports:
      - 3333:3333
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=${NODE_PORT}
      - REDIS=${REDIS}
      - REDIS_PORT=${REDIS_PORT}
      - DB=${DB}
      - ORG_URL=${ORG_URL}
      - OKTA_TOKEN=${OKTA_TOKEN}
      - SESSION_SECRET=${SESSION_SECRET}
      - OKTA_ISSUER=${OKTA_ISSUER}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
      - OKTA_REDIRECT_URL=${OKTA_REDIRECT_URL}
    command:
      sh -c 'npm i && npm start'
    links:
      - redis
  pwa:
    image: httpd:2.4
    volumes:
      - ./pwa/komunat-pwa/komunat/www/:/usr/local/apache2/htdocs/
    ports:
      - 81:80
    restart: always
    links:
      - pwa-backend
  
  redis:
    image: redis:5.0.4-alpine
    volumes:
      - ./esabatad:/data
    restart: always
    entrypoint: redis-server --appendonly yes